version: "3.7"
services:
  wireguard:
    privileged: true
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - ./wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
      - 3128:3128
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - backend
  proxy:
    depends_on:
      - wireguard
    environment:
      PROXY_USERNAME: foo
      PROXY_PASSWORD: bar
    build: .
    network_mode: service:wireguard

networks:
  backend:
    driver: bridge
